import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const source=fs.readFileSync(path.join(root,'apps/web/src/hud-preview.ts'),'utf8').replace(/^import .*;\r?\n/gm,'');
const context={exports:{}};vm.createContext(context);vm.runInContext(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,context);
const values={role:'low',hp:'50',mp:'50',xp:'25',weight:'50',hunger:'3',daylight:'0'};
const listeners=new Map(),calls=[],snapshots=[];
const controls={querySelector:s=>({value:values[s.match(/preview-(.*?)\]/)[1]]}),addEventListener:(t,f)=>listeners.set(t,f),removeEventListener:(t,f)=>{if(listeners.get(t)===f)listeners.delete(t);}};
const base={job:2,level:99,maxHp:100,maxMp:50,maxExperience:200,maxWeight:80};
const dispose=context.exports.bindHudPreviewControls(controls,base,{replaceAttributes:a=>snapshots.push(a),hungerStatus:h=>calls.push(['hunger',h]),daylight:(p,d)=>calls.push(['daylight',p,d])},(a,interactive)=>calls.push(['changed',interactive]));
assert.equal(snapshots[0].level,27);assert.equal(snapshots[0].hp,50);assert.equal(snapshots[0].mp,25);assert.equal(snapshots[0].experience,50);assert.equal(snapshots[0].weight,40);assert.equal(base.level,99);assert.deepEqual(calls,[['hunger',3],['daylight',0,0],['changed',false]]);
console.log('PASS: calibration controls drive production HUD APIs with isolated percentage fixtures and morning zero');
values.role='high';listeners.get('change')();assert.equal(snapshots.at(-1).level,28);assert.equal(calls.at(-1)[1],true);
values.role='mage';values.hp='0';values.weight='100';listeners.get('input')();assert.equal(snapshots.at(-1).job,1);assert.equal(snapshots.at(-1).hp,0);assert.equal(snapshots.at(-1).weight,80);
console.log('PASS: role threshold and resource controls update the same fixture snapshot for character window and HUD');
dispose();assert.equal(listeners.size,0);
const html=fs.readFileSync(path.join(root,'apps/web/ui-calibration.html'),'utf8');assert.ok(html.includes('data-hud-preview-role'));assert.equal((html.match(/data-hud-orb-image/g)||[]).length,2);assert.equal(fs.readFileSync(path.join(root,'apps/web/play.html'),'utf8').includes('data-hud-preview-role'),false);
console.log('PASS: calibration has production globe background nodes and its controls dispose without entering play UI');
