import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const context={exports:{}};vm.createContext(context);
vm.runInContext(ts.transpileModule(fs.readFileSync('apps/web/src/mining-controller.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);
const {MiningController,miningEligible,miningDirection,miningInterval,orePurity}=context.exports;
let time=0,serial=10,timeout=0;
let state={x:12,y:18,direction:4,mapGeneration:3,dead:false,weapon:{shape:19,stdMode:6,durability:9000},canAct:true,serverReady:true,level:1,hitSpeed:0};
const sent=[],canWalk=(x,y)=>x!==13||y!==18;
const controller=new MiningController({read:()=>state,canWalk,now:()=>time,timeout:()=>timeout++,send:direction=>{sent.push(direction);return {actionId:++serial,mapGeneration:state.mapGeneration};}});
const wall={x:13,y:18,shift:false,targetPresent:false};
assert.equal(miningEligible(state,wall,canWalk),true);
assert.equal(miningEligible(state,{...wall,x:12,y:19},canWalk),false);
assert.equal(miningEligible(state,{...wall,x:12,y:19,shift:true},canWalk),true);
for(const patch of [{dead:true},{horse:true},{weapon:{shape:18,stdMode:6,durability:10}},{weapon:{shape:19,stdMode:6,durability:0}}])
 assert.equal(miningEligible({...state,...patch},wall,canWalk),false);
assert.equal(miningEligible(state,{...wall,targetPresent:true},canWalk),false);
const expected=[[12,17],[13,17],[13,18],[13,19],[12,19],[11,19],[11,18],[11,17]];
expected.forEach(([x,y],i)=>assert.equal(miningDirection(state,{x,y}),i));
assert.equal(miningInterval(state),1386);assert.equal(miningInterval({...state,level:99,hitSpeed:9}),600);
assert.equal(miningInterval({...state,attackSlow:true}),2886);
assert.equal(miningInterval({...state,hitSpeed:-5}),1686);
console.log('PASS native wall/Shift/no-target/tool/life eligibility, all eight directions and native request cadence');
assert.equal(controller.start(wall),true);assert.deepEqual(sent,[2]);
for(let i=0;i<5;i++){time+=500;controller.tick();}
assert.deepEqual(sent,[2]);
assert.equal(controller.settle({actionId:11,mapGeneration:3,kind:'attack',accepted:true}),false);
assert.equal(controller.settle({actionId:11,mapGeneration:2,kind:'mine',accepted:true}),false);
assert.equal(controller.settle({actionId:10,mapGeneration:3,kind:'mine',accepted:true}),false);
assert.equal(controller.settle({actionId:11,mapGeneration:3,kind:'mine',accepted:true}),true);
state.canAct=false;controller.tick();assert.equal(sent.length,1);
state.canAct=true;state.serverReady=false;controller.tick();assert.equal(sent.length,1);
state.serverReady=true;controller.tick();assert.equal(sent.length,2);
console.log('PASS exactly one native pending action, matching identity, animation and shared server action gates');
controller.cancel();
assert.equal(controller.debugState().active,false);assert.ok(controller.debugState().pending);
assert.equal(controller.start(wall),true);assert.equal(sent.length,2);
controller.cancel();controller.settle({actionId:12,mapGeneration:3,kind:'mine',accepted:true});
time+=2000;controller.tick();assert.equal(sent.length,2);
controller.start(wall);assert.equal(sent.length,3);
assert.equal(controller.reject({actionId:13,mapGeneration:3}),true);assert.equal(controller.debugState().active,false);
console.log('PASS cancellation drains the native slot; late success cannot restart; rejection stops auto mining');
controller.start(wall);time+=2000;controller.tick();
state.weapon.durability=0;controller.tick();assert.equal(controller.debugState().active,false);
controller.reset();state.weapon.durability=9000;controller.start(wall);
state.mapGeneration=4;controller.tick();assert.equal(controller.debugState().active,false);
controller.reset();assert.equal(controller.debugState().pending,undefined);
state.dead=true;assert.equal(controller.start(wall),false);state.dead=false;
controller.start(wall);time+=5000;controller.tick();assert.equal(timeout,1);
assert.equal(controller.debugState().pending,undefined);assert.equal(controller.debugState().active,false);
console.log('PASS tool break, death, map reset and timeout stop safely; timeout asks the production connection to close');
for(const [raw,purity] of [[3000,3],[3499,3],[3500,4],[4500,4],[9500,10],[15999,16],[24999,25]])
 assert.equal(orePurity({stdMode:43,durability:raw}),purity);
assert.equal(orePurity({stdMode:6,durability:9500}),undefined);
console.log('PASS raw server ore quality uses original Delphi round-to-even without fabricating inventory');
