import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import ts from 'typescript';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const layout=JSON.parse(fs.readFileSync(path.join(root,'content/classic-176/ui-layout.json'),'utf8'));
const library=JSON.parse(fs.readFileSync(path.join(root,'assets/web/ui-national/prguse/library.json'),'utf8'));
const hud=fs.readFileSync(path.join(root,'apps/web/src/classic-hud.ts'),'utf8');
const play=fs.readFileSync(path.join(root,'apps/web/src/play.ts'),'utf8');
const gateway=fs.readFileSync(path.join(root,'services/web-gateway/GatewaySession.cs'),'utf8');
const markup=fs.readFileSync(path.join(root,'apps/web/play.html'),'utf8');
const calibrationMarkup=fs.readFileSync(path.join(root,'apps/web/ui-calibration.html'),'utf8');
const calibrationSource=fs.readFileSync(path.join(root,'apps/web/src/ui-calibration.ts'),'utf8');
const css=fs.readFileSync(path.join(root,'apps/web/src/style.css'),'utf8');
const guildListModule={exports:{}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(root,'apps/web/src/guild-list.ts'),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports:guildListModule.exports});

{
 const source=ts.createSourceFile('classic-hud.ts',hud,ts.ScriptTarget.Latest,true),classNode=source.statements.find(node=>ts.isClassDeclaration(node)&&node.name?.text==='ClassicHud');assert.ok(classNode,'ClassicHud source class missing');
 const method=name=>classNode.members.find(node=>ts.isMethodDeclaration(node)&&node.name&&ts.isIdentifier(node.name)&&node.name.text===name)?.getText(source);
 const skinWindow=method('skinWindow'),flushPending=method('applyPendingWindowSkins');assert.ok(skinWindow&&flushPending,'window skin race handlers missing');
 const harness=ts.transpileModule(`class Harness{${skinWindow}\n${flushPending}}`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context={};vm.createContext(context);vm.runInContext(`${harness}\nthis.Harness=Harness;`,context);
 const instance=vm.runInContext('new Harness()',context),element={};instance.nationalReady=false;instance.libraries=new Map();instance.nationalLibraries=new Map();instance.pendingWindowSkins=new Map();
 instance.skinWindow(element,'guild');assert.equal(instance.pendingWindowSkins.get(element),'guild','an early-opened window must wait for its UI libraries');
 const retried=[];instance.nationalReady=true;instance.skinWindow=(window,kind)=>retried.push([window,kind]);instance.applyPendingWindowSkins();assert.deepEqual(retried,[[element,'guild']]);assert.equal(instance.pendingWindowSkins.size,0);
 assert.match(hud,/this\.render\(\);\s*this\.applyPendingWindowSkins\(\);/,'pending windows must be reskinned after the shared asset session settles');
 console.log('PASS: windows opened during asset loading are reskinned once native atlases finish loading');
}

for(const [kind,index,width,height] of [['group',120,276,242],['guild',180,628,453]]){
 const window=layout.nationalUtilityWindows[kind],frame=library.frames[String(index)];
 assert.ok(window,`${kind} native window contract missing`);
 assert.ok(frame,`Prguse#${index} is not exported`);
 assert.equal(layout.nationalWindowContracts[kind].frame,`prguse#${index}`);
 assert.deepEqual([frame.width,frame.height],[width,height],`Prguse#${index} asset dimensions changed`);
 assert.deepEqual([window.index,window.width,window.height],[index,width,height],`${kind} window no longer uses its native frame dimensions`);
 if(kind==='group')assert.ok(Math.abs(window.x*2+width-800)<=1&&Math.abs(window.y*2+height-600)<=1,'group window must remain centered on the 800x600 stage');
 else assert.deepEqual([window.x,window.y],[0,-3],'guild window must open at the native ShowGuildDlg origin');
 assert.ok(fs.existsSync(path.join(root,'assets/web/ui-national/prguse',frame.file)),`Prguse#${index} image is missing`);
}
{
 const guild=layout.nationalUtilityWindows.guild,scroll=guild.scrollButtons,step=guildListModule.exports.scrollGuildMemberList;
 assert.deepEqual([scroll.stepRows,scroll.lineHeight],[3,14]);
 assert.deepEqual([scroll.up.x,scroll.up.y,scroll.up.width,scroll.up.height,scroll.down.x,scroll.down.y,scroll.down.width,scroll.down.height],[588,230,40,40,588,280,40,40]);
 const nativeButtons={open:[27,387],members:[27,407],chat:[112,407],add:[235,387],remove:[235,407],notice:[320,387],ranks:[320,407],ally:[404,387],breakAlly:[404,407],war:[488,387]};
 for(const [name,[x,y]] of Object.entries(nativeButtons))assert.deepEqual([guild.buttons[name].geometry.x,guild.buttons[name].geometry.y,guild.buttons[name].geometry.width,guild.buttons[name].geometry.height],[x,y,64,16],`${name} must use its native guild-window position`);
 assert.match(hud,/const geometry=frames\.geometry;if\(geometry\)\{button\.style\.left=/,'native guild button coordinates must be applied by the production renderer');
 assert.match(css,/grid-template-rows:28px minmax\(0,1fr\) 62px/,'guild roster and management content must leave the native bottom action strip clear');
 assert.match(css,/\.guild-panel button\.native-frame-button\{position:absolute/,'native guild buttons must be positioned independently of the web form layout');
 assert.match(hud,/layout\.nationalUtilityWindows\.guild\.scrollButtons/);
 assert.match(play,/function scrollGuildWindow\(direction:-1\|1\)\{const list=guildChatMode\?guildChatLog:guildMembers;return scrollGuildMemberList\(list,direction,guildScrollSpec\.stepRows,guildScrollSpec\.lineHeight\);\}/,'guild arrows must scroll whichever roster or chat page is active');
 assert.match(markup,/id="guild-scroll-up"[^>]+aria-controls="guild-members"/);
 assert.match(markup,/id="guild-scroll-down"[^>]+aria-controls="guild-members"/);
 const list={scrollTop:0,scrollHeight:560,clientHeight:364,querySelector:()=>({getBoundingClientRect:()=>({height:14})})};
 assert.equal(step(list,1,scroll.stepRows,scroll.lineHeight),42,'the down arrow should advance exactly three 14px lines');
 assert.equal(step(list,-1,scroll.stepRows,scroll.lineHeight),0,'the up arrow should return three lines without underflow');
 assert.equal(step(list,1,scroll.stepRows,scroll.lineHeight),42);
 assert.equal(step(list,1,scroll.stepRows,scroll.lineHeight),84);
 assert.equal(step(list,1,scroll.stepRows,scroll.lineHeight),126);
 assert.equal(step(list,1,scroll.stepRows,scroll.lineHeight),168);
 assert.equal(step(list,1,scroll.stepRows,scroll.lineHeight),196,'the down arrow should clamp at the list end');
 assert.equal(step(list,-1,scroll.stepRows,scroll.lineHeight),154);
 console.log('PASS: guild window restores its inset and embedded three-line roster arrows');
}
{
 const assetCallback=play.indexOf("const tradeIconAssets=new ItemIconAssets('items',()=>{if(inventory)renderTrade();});"),inventoryCreation=play.indexOf('inventory=new InventoryView('),initialTradeRender=play.indexOf('renderTrade();',inventoryCreation);
 assert.ok(assetCallback>=0&&play.indexOf('let inventory!:InventoryView;',0)<assetCallback,'trade icon readiness must see an initialized lexical binding');
 assert.ok(inventoryCreation>assetCallback&&initialTradeRender>inventoryCreation,'trade should first render after its inventory controller exists');
 console.log('PASS: asynchronous item-icon readiness cannot render trade before inventory initialization');
}
{
 const window=layout.nationalUtilityWindows.trade,contract=layout.nationalWindowContracts.trade;
 for(const [index,width,height] of [[389,236,175],[390,220,175],[391,44,16],[28,36,21]]){
  const frame=library.frames[String(index)];assert.ok(frame,`trade frame ${index} is not exported`);assert.deepEqual([frame.width,frame.height],[width,height],`trade frame ${index} dimensions changed`);
  assert.ok(fs.existsSync(path.join(root,'assets/web/ui-national/prguse',frame.file)),`trade frame ${index} image is missing`);
 }
 assert.equal(contract.frame,'prguse#389+390');assert.equal(window.index,389);assert.equal(window.x,564);assert.equal(window.remote.index,390);assert.equal(window.remote.left,-220);
 assert.deepEqual([window.grid.columns,window.grid.rows,window.grid.left,window.grid.top,window.grid.cellWidth,window.grid.cellHeight],[5,2,21,56,36,33]);
 assert.deepEqual([window.confirm.index,window.confirm.left,window.confirm.top,window.confirm.width,window.confirm.height],[391,155,128,44,16]);
 assert.match(hud,/data-trade-remote-window/);assert.match(hud,/layout\.nationalUtilityWindows\.trade\.confirm\.index/);
 assert.match(markup,/data-trade-remote-window/);assert.match(markup,/data-trade-confirm/);assert.match(markup,/id="trade-remote-gold"/);
 assert.match(css,/classic-window\[data-window-kind=trade\]\{display:block;overflow:visible/);assert.match(css,/trade-remote-items[^\n]*left:-199px/);
 console.log('PASS: trade uses native paired frames and the reference-source 5x2 offer-grid and confirmation coordinates');
}
{
 const sourceFile=ts.createSourceFile('play.ts',play,ts.ScriptTarget.Latest,true),compile=text=>ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 const declaration=name=>sourceFile.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name)?.getText(sourceFile);
 const render=declaration('renderTrade'),ensure=declaration('ensureTradeSlots'),release=declaration('releasePendingTradeItem');assert.ok(render,'production renderTrade function missing');assert.ok(ensure,'production offer-slot allocator missing');assert.ok(release,'production pending trade-item release helper missing');assert.ok(!render.includes("showClassicWindow('trade')"),'trade refresh must not reopen or steal focus');
 class Node{constructor(){this.hidden=false;this.disabled=false;this.dataset={};this.children=[];this.attributes={};this.value='';this.textContent='';this.title='';}replaceChildren(...children){this.children=[...children];}append(...children){this.children.push(...children);}setAttribute(key,value){this.attributes[key]=value;}}
 const remoteGold=new Node(),nodes={},tooltipItems=[],offered=[],resolved=[];const context={tradeOpen:false,tradeTarget:new Node(),tradeGold:0,tradeRemoteGold:0,tradePanel:new Node(),tradeStatus:new Node(),tradeRequestForm:new Node(),tradeRequestButton:new Node(),tradeGoldInput:new Node(),tradeSetGold:new Node(),tradeAccept:new Node(),tradeCancel:new Node(),tradeLocalItems:new Node(),tradeRemoteItems:new Node(),tradeIconAssets:{},tradeLocal:new Map(),tradeRemote:new Map(),tradeLocalSlots:new Map(),tradeRemoteSlots:new Map(),tradeAccepted:false,tradePendingAction:null,tradePendingMakeIndex:undefined,tradePendingTimedOut:false,tradeRequestPending:false,tradeRequestTimedOut:false,tradeCancelPending:false,nearbyTradeButtons:[],worldCommandsAvailable:()=>true,inventory:{heldItem:()=>context.held,offerToTrade:id=>{offered.push(id);return true;},consumeHeldItem:()=>true,resolve:(...args)=>{resolved.push(args);return true;}},held:undefined,attachItemTooltip:(node,item,label)=>tooltipItems.push([item.makeIndex,label]),sendTradeMutation:(action,message)=>context.sent.push({action,...message}),socket:{send:value=>context.sent.push(JSON.parse(value))},sent:[],document:{createElement:()=>new Node(),querySelector:selector=>selector==='#trade-remote-gold'?remoteGold:(nodes[selector]??=new Node())},itemIconElement:item=>{const icon=new Node();icon.alt=item.name;return icon;}};
 context.tradeTarget.value='Tao905';context.tradeLocal.set(4,{makeIndex:4,name:'木剑',looks:1});context.tradeLocal.set(5,{makeIndex:5,name:'铁剑',looks:2});context.tradeRemote.set(8,{makeIndex:8,name:'小量金创药',looks:3});context.tradePanel.hidden=true;
 vm.createContext(context);vm.runInContext(compile(`${ensure}\n${release}\n${render}\nrenderTrade()`),context);
 assert.equal(context.tradePanel.dataset.tradeOpen,'false');assert.equal(context.tradePanel.hidden,true,'state rendering must preserve an explicitly hidden utility window');assert.equal(context.tradeRequestForm.hidden,false);assert.equal(context.tradeAccept.hidden,true);assert.equal(context.tradeSetGold.disabled,true);assert.equal(context.tradeLocalItems.children.length,10);assert.equal(context.tradeRemoteItems.children.length,10);assert.equal(context.tradeLocalItems.children[0].dataset.itemId,'4');assert.equal(context.tradeLocalItems.children[1].dataset.itemId,'5');assert.equal(context.tradeLocalItems.children[0].children[0].children.length,2);assert.equal(context.tradeRemoteItems.children[0].dataset.itemId,'8');assert.equal(context.tradeRemoteItems.children[0].children[0].disabled,false);assert.equal(context.tradeRemoteItems.children[0].children[0].tabIndex,0);
 context.tradeOpen=true;vm.runInContext(compile('renderTrade()'),context);assert.equal(context.tradePanel.dataset.tradeOpen,'true');assert.equal(context.tradePanel.hidden,true,'a live offer update must not reveal a hidden trade panel');assert.equal(context.tradeRequestForm.hidden,true);assert.equal(context.tradeAccept.hidden,false);assert.equal(context.tradeSetGold.disabled,false);assert.equal(remoteGold.textContent,'金币 0');
 context.tradePanel.hidden=false;vm.runInContext(compile('renderTrade()'),context);assert.equal(context.tradePanel.hidden,false,'rendering must leave an explicitly opened panel visible');context.tradePanel.hidden=true;context.tradeRemote.set(9,{makeIndex:9,name:'小量魔法药',looks:3});vm.runInContext(compile('renderTrade()'),context);assert.equal(context.tradePanel.hidden,true,'remote item arrival must not reopen a window hidden by the user');
 context.tradeLocalItems.children[0].children[0].onclick();assert.deepEqual(context.sent,[{action:'remove',type:'tradeRemove',makeIndex:4}]);
 context.held={makeIndex:44};context.tradeLocalItems.children[2].children[0].onclick();assert.deepEqual(offered,[44]);let dropped='45';context.tradeLocalItems.children[3].children[0].ondragover({preventDefault(){this.prevented=true;},dataTransfer:{}});context.tradeLocalItems.children[3].children[0].ondrop({preventDefault(){this.prevented=true;},stopPropagation(){},dataTransfer:{getData:()=>dropped}});assert.deepEqual(offered,[44,45]);context.held={makeIndex:46};vm.runInContext(compile('renderTrade()'),context);const occupiedOffer=context.tradeLocalItems.children[1].children[0];assert.match(occupiedOffer.className,/drop-target/);assert.match(occupiedOffer.attributes['aria-label'],/放入选中的背包物品/);occupiedOffer.onclick();assert.deepEqual(offered,[44,45,46],'a selected bag item dropped on an occupied trade slot must be offered instead of removing the existing offer');assert.equal(context.sent.length,1,'offering onto an occupied cell must not send a remove request for that cell');dropped='47';let dragAccepted=false,dragStopped=false;occupiedOffer.ondragover({preventDefault(){dragAccepted=true;},dataTransfer:{}});assert.equal(dragAccepted,true,'an occupied local trade slot must accept a bag-item drag while offers are unlocked');occupiedOffer.ondrop({preventDefault(){},stopPropagation(){dragStopped=true;},dataTransfer:{getData:()=>dropped}});assert.equal(dragStopped,true,'the trade drop must not leak to the enclosing panel');assert.deepEqual(offered,[44,45,46,47],'dragging onto an occupied local offer adds the dragged item instead of removing the existing offer');context.held=undefined;vm.runInContext(compile('renderTrade()'),context);
 context.tradeLocal.delete(4);vm.runInContext(compile('renderTrade()'),context);assert.equal(context.tradeLocalItems.children[0].dataset.itemId,undefined,'removing a leading item must leave its old native cell empty');assert.equal(context.tradeLocalItems.children[1].dataset.itemId,'5','later offers must stay anchored to their previous cells');
 context.tradePendingAction='gold';vm.runInContext(compile('renderTrade()'),context);let lockedDropAccepted=false;const lockedOffer=context.tradeLocalItems.children[1].children[0];lockedOffer.ondragover({preventDefault(){lockedDropAccepted=true;},dataTransfer:{}});lockedOffer.ondrop({preventDefault(){lockedDropAccepted=true;},stopPropagation(){},dataTransfer:{getData:()=> '48'}});assert.equal(lockedDropAccepted,false,'offer mutation lock must also reject native drag/drop');assert.deepEqual(offered,[44,45,46,47]);assert.equal(context.tradeAccept.disabled,true);assert.equal(context.tradeGoldInput.disabled,true);assert.equal(context.tradeLocalItems.children[1].children[0].attributes['aria-disabled'],'true');assert.equal(context.tradeLocalItems.children[1].children[0].disabled,false,'offer icons remain keyboard-focusable for their tooltip while locked');assert.equal(context.tradeLocalItems.children[2].children[0].disabled,true);assert.equal(context.tradeCancel.disabled,false);assert.match(context.tradeStatus.textContent,/正在同步交易报价/);
 context.tradePendingTimedOut=true;vm.runInContext(compile('renderTrade()'),context);assert.match(context.tradeStatus.textContent,/状态未确认/);assert.equal(context.tradePanel.dataset.tradePending,'gold');
 context.tradePendingAction=null;context.tradePendingTimedOut=false;context.tradeAccepted=true;context.tradeCancelPending=true;vm.runInContext(compile('renderTrade()'),context);assert.equal(context.tradeAccept.disabled,true);assert.equal(context.tradeSetGold.disabled,true);assert.equal(context.tradePanel.dataset.tradeAccepted,'true');assert.equal(context.tradePanel.dataset.tradeCancelPending,'true');assert.equal(context.tradeAccept.textContent,'已确认');assert.equal(context.tradeAccept.attributes['aria-pressed'],'true');assert.match(context.tradeStatus.textContent,/正在取消交易/);
 assert.match(gateway,/Trade offer update is still pending/);assert.match(gateway,/Trade is already confirmed/);assert.match(gateway,/Trade is confirmed; cancel the trade before changing the offer/);
 assert.deepEqual(tooltipItems.slice(0,3),[[4,'我方交易物品'],[5,'我方交易物品'],[8,'对方交易物品']]);context.tradePendingMakeIndex=44;vm.runInContext('releasePendingTradeItem()',context);assert.deepEqual(resolved,[[44,false,false]]);assert.equal(context.tradePendingMakeIndex,undefined);
 context.slotRepairItems=new Map([[7,{makeIndex:7}],[8,{makeIndex:8}],[9,{makeIndex:9}]]);context.slotRepairMap=new Map([[7,8],[8,8],[9,-1],[100,4]]);const repaired=vm.runInContext('ensureTradeSlots(slotRepairItems,slotRepairMap)',context);assert.equal(repaired.size,3);assert.equal(context.slotRepairMap.get(7),8);assert.equal(context.slotRepairMap.get(8),0);assert.equal(context.slotRepairMap.get(9),1);assert.equal(context.slotRepairMap.has(100),false);assert.equal(context.tradeLocalSlots.get(5),1);
  assert.match(play,/renderTrade\(\);showClassicWindow\('trade'\)/,'the authoritative trade-open event must explicitly reveal the window');assert.match(play,/const standaloneUtilityWindowIds=new Set\(\['group','guild','trade'\]\)/);assert.match(markup,/id="group-panel"[^>]*hidden[^>]*><strong>队伍<\/strong><button[^>]*data-window-close="group"/);assert.match(markup,/id="guild-panel"[^>]*hidden[^>]*><strong>行会<\/strong><button[^>]*data-window-close="guild"/);assert.match(markup,/id="trade-panel"[^>]*hidden[^>]*><div class="trade-heading"><strong>玩家交易<\/strong><button[^>]*data-window-close="trade"/);assert.match(css,/national-window\.classic-utility-window\[hidden\]\{display:none!important\}/);assert.match(markup,/id="trade-status" role="status" aria-live="polite"/);assert.match(css,/trade-accept\[aria-pressed=true\]:disabled/);
 console.log('PASS: trade rendering locks in-flight and confirmed offers, keeps cancel available, and gateway rejects premature or duplicate confirmation');
}
{
 const sourceFile=ts.createSourceFile('play.ts',play,ts.ScriptTarget.Latest,true),declaration=sourceFile.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='showClassicWindow');assert.ok(declaration,'production utility window router missing');
 const vmSource=ts.transpileModule(declaration.getText(sourceFile),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,fronted=[],skinned=[],tabs=Array.from({length:3},()=>({dataset:{},classList:{toggle(){}}}));
 const node=id=>({id,hidden:true,style:{}}),trade=node('trade-panel'),guild=node('guild-panel'),group=node('group-panel'),quest=node('quest-panel'),chat=node('chat-panel'),attack=node('attack-panel'),classicWindow=node('classic-window'),context={classicWindowSources:[{id:'quest',label:'任务',node:quest},{id:'chat',label:'聊天',node:chat},{id:'group',label:'队伍',node:group},{id:'attack',label:'攻击',node:attack},{id:'guild',label:'行会',node:guild},{id:'trade',label:'交易',node:trade}],standaloneUtilityWindowIds:new Set(['group','guild','trade']),classicWindow,classicWindowBody:{append(){}},classicWindowTitle:{textContent:''},classicHud:{skinWindow:(element,id)=>skinned.push([element.id,id])},bringClassicWindowToFront:element=>fronted.push(element.id),dockChat(){},document:{querySelectorAll:()=>tabs}};vm.createContext(context);vm.runInContext(vmSource+'\nshowClassicWindow("trade");showClassicWindow("guild");showClassicWindow("quest")',context);
 assert.equal(trade.hidden,false);assert.equal(guild.hidden,false);assert.equal(quest.hidden,false);assert.equal(classicWindow.hidden,false);assert.equal(group.hidden,true);assert.equal(attack.hidden,true);assert.deepEqual(skinned,[['trade-panel','trade'],['guild-panel','guild'],['classic-window','quest']]);assert.deepEqual(fronted,['trade-panel','guild-panel','classic-window']);
 console.log('PASS: production window routing keeps party, guild, and trade as separately skinned windows while generic utility pages remain in their own window');
}
{
 const sourceFile=ts.createSourceFile('play.ts',play,ts.ScriptTarget.Latest,true),declaration=name=>sourceFile.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name)?.getText(sourceFile),resolve=declaration('resolveTradeMutation'),send=declaration('sendTradeMutation');assert.ok(resolve&&send,'production trade mutation helpers missing');
 const sent=[],context={tradeOpen:true,tradeAccepted:false,tradePendingAction:null,tradePendingMakeIndex:undefined,tradePendingTimedOut:false,tradeOperationTimer:undefined,tradeLocal:new Map(Array.from({length:10},(_,index)=>[index,{makeIndex:index}])),worldCommandsAvailable:()=>true,connection:{textContent:''},renderTrade(){},window:{setTimeout:()=>19},clearTimeout(){},socket:{send:value=>sent.push(JSON.parse(value))}};vm.createContext(context);vm.runInContext(ts.transpileModule(`${resolve}\n${send}`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);
 assert.equal(vm.runInContext("sendTradeMutation('add',{type:'tradeAdd',makeIndex:44})",context),false);assert.equal(context.connection.textContent,'我方交易栏已满');assert.equal(sent.length,0);
 context.tradeLocal.clear();assert.equal(vm.runInContext("sendTradeMutation('add',{type:'tradeAdd',makeIndex:44})",context),true);assert.deepEqual(sent,[{type:'tradeAdd',makeIndex:44}]);assert.equal(context.tradePendingAction,'add');assert.equal(context.tradePendingMakeIndex,44);
 console.log('PASS: a full ten-cell offer is rejected locally; a free slot starts one authoritative add request');
}
{
 const sourceFile=ts.createSourceFile('play.ts',play,ts.ScriptTarget.Latest,true),declaration=sourceFile.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='closeUtilityWindow');assert.ok(declaration,'production standalone utility close helper missing');
 const vmSource=ts.transpileModule(declaration.getText(sourceFile),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
 const calls=[],tradeWindow={hidden:false},context={tradeOpen:true,tradeCancel:{click:()=>calls.push('cancel')},standaloneUtilityWindowIds:new Set(['trade']),classicWindowSources:[{id:'trade',node:tradeWindow}]};vm.createContext(context);vm.runInContext(vmSource+"\ncloseUtilityWindow('trade')",context);assert.deepEqual(calls,['cancel']);assert.equal(tradeWindow.hidden,false);
 context.tradeOpen=false;vm.runInContext("closeUtilityWindow('trade')",context);assert.deepEqual(calls,['cancel']);assert.equal(tradeWindow.hidden,true);
 console.log('PASS: closing a standalone active trade requests authoritative cancellation; an idle trade invite only hides that window');
}
assert.match(hud,/layout\.nationalUtilityWindows\.group\.index/);
assert.match(hud,/layout\.nationalUtilityWindows\.guild\.index/);
assert.match(hud,/element\.dataset\.windowKind=kind/);
assert.match(hud,/--classic-window-background/);
assert.match(hud,/--classic-window-width/);
assert.match(play,/groupMode\.dataset\.enabled=groupEnabled\?'true':'false'/);
assert.match(play,/classicHud\.skinWindow\(classicWindow,id\)/);
for(const control of ['group-mode','group-create','group-add','group-remove','group-members','guild-open','guild-members-request','guild-chat-toggle','guild-chat-log','guild-create','guild-add','guild-remove','guild-war-request','guild-castle-dialogue','guild-notice-save','guild-ally','guild-break-ally','guild-ranks-save','guild-members'])
 assert.ok(markup.includes(`id="${control}"`),`${control} interaction disappeared from play page`);
assert.doesNotMatch(markup,/id="guild-ally-target"/,'alliance must use the native adjacent-leader confirmation instead of an unused target field');
assert.match(play,/guildAlly\.addEventListener\('click',\(\)=>confirmGuildAction\('ally'\)\)/);
assert.match(play,/guildBreakAlly\.addEventListener\('click',\(\)=>confirmGuildAction\('breakAlly'\)\)/);
assert.doesNotMatch(markup,/id="group-target"/,'party member names belong in the original modal entry, not a permanent field on the native window');
assert.doesNotMatch(markup,/id="guild-target"/,'guild member names belong in the original modal entry, not a permanent field on the native window');
assert.match(play,/systemDialog\.showInput\(\{text:prompts\[type\],buttons:\['ok','cancel'\],size:'horizontal'/,'party actions must use the shared native input prompt');
assert.match(play,/systemDialog\.showInput\(\{text,buttons:\['ok','cancel'\],size:'horizontal',input:\{label:'角色名',maxLength:10,inputMode:'text'\}\}\)/,'guild member actions must use the shared native input prompt');
const calibrationParty=calibrationMarkup.match(/<section id="calibration-group-panel"[\s\S]*?<\/section>/)?.[0];assert.ok(calibrationParty,'calibration party fixture must exist');
assert.doesNotMatch(calibrationParty,/<input\b/,'calibration party window must not retain the removed permanent name field');
for(const id of ['group-mode','group-create','group-add','group-remove','group-feedback','group-members'])assert.match(calibrationParty,new RegExp(`id="${id}"`),`calibration must use the production ${id} contract`);
assert.match(calibrationParty,/id="group-create"[^>]*disabled/,'the existing-party fixture must not offer create-group');
assert.match(calibrationSource,/systemDialog\.showInput\(\{text,buttons:\['ok','cancel'\],size:'horizontal',input:\{label:'角色名',maxLength:10,inputMode:'text'\}\}\)/,'calibration group actions must exercise the shared native name dialog');
for(const prompt of ['请输入邀请加入小组的玩家名.','键入您想要参加小组的名字 .','键入您想要从小组被删除的名字.'])assert.ok(calibrationSource.includes(prompt),`calibration input prompt missing: ${prompt}`);
assert.match(css,/classic-window-tabs\{position:absolute;left:calc\(100% \+ 6px\)/,'party window must retain an accessible utility switcher outside its compact art');
assert.match(css,/classic-window-tabs\{position:relative;display:flex;flex-wrap:nowrap/,'guild window must keep the utility switcher while using its wider native frame');
assert.ok(css.includes('#group-members')&&css.includes('top:72px'),'party roster must stay within the native member-list area');
assert.match(css,/guild-management\{display:flex;min-width:0;min-height:0;flex-wrap:wrap;align-content:flex-start;align-items:center;gap:4px;padding:5px;overflow:auto/);
assert.match(css,/\.guild-create\[hidden\],[\s\S]*?\.guild-invites\[hidden\],[\s\S]*?\.guild-management\[hidden\]\{display:none!important\}/,'guild row state must override the native flex layout when hidden');
assert.match(css,/\.guild-window-roster>\[hidden\]\{display:none!important\}/,'guild page switches must hide the inactive roster or chat list despite the native list styles');
console.log('PASS: party and guild windows use native frames, reference placement, and reachable actions');

{
 const buttons=layout.nationalUtilityWindows.guild.buttons;
 for(const [action,pair] of Object.entries(buttons)){
  for(const index of [pair.normal,pair.hover]){const frame=library.frames[String(index)];assert.ok(frame,`guild ${action} frame ${index} is missing`);assert.deepEqual([frame.width,frame.height],[64,16],`guild ${action} frame ${index} has unexpected dimensions`);assert.ok(fs.existsSync(path.join(root,'assets/web/ui-national/prguse',frame.file)),`guild ${action} frame ${index} image is missing`);}
 }
 assert.match(hud,/skinNativeFrameButton\(button,prguse,frames\.normal,frames\.hover\)/);assert.match(css,/button\.native-frame-button\[data-ui-state=pressed\]/);
assert.match(hud,/if\(!this\.nationalReady\)\{[\s\S]*?bindNativeFrameButtonStates\(button,paint\)/,'fallback HUD window buttons must use pointer-aware native states');
assert.match(hud,/const paintState=\(state:NativeButtonVisualState\)=>\{[\s\S]*?state==='normal'\?spec\.index:state==='hover'\?spec\.hover:spec\.pressed[\s\S]*?bindNativeFrameButtonStates\(button,paintState\)/,'national HUD buttons must route normal, hover, and pressed frames through the pointer state helper');
assert.doesNotMatch(hud,/button\.onmouseenter=\(\)=>paint\(/,'national HUD controls must not retain mouse-only state handlers');
 const sourceFile=ts.createSourceFile('play.ts',play,ts.ScriptTarget.Latest,true),compile=text=>ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 const declaration=name=>sourceFile.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name)?.getText(sourceFile);
 const functions=['guildRanksText','syncGuildNotice','syncGuildRanks','beginGuildAction','resolveGuildAction','confirmGuildMemberAction','confirmGuildAction','cancelGuildActionPrompt','sendGuild','guildActionForCommand','guildActionForResult','handleGuildCommandError','appendGuildChatEntry','renderGuildChat','setGuildChatMode','toggleGuildChat','recordGuildChat','scrollGuildWindow','renderGuild'].map(declaration).join('\n');
 for(const name of ['guildRanksText','syncGuildNotice','syncGuildRanks','beginGuildAction','resolveGuildAction','confirmGuildMemberAction','confirmGuildAction','cancelGuildActionPrompt','sendGuild','guildActionForCommand','guildActionForResult','handleGuildCommandError','appendGuildChatEntry','renderGuildChat','setGuildChatMode','toggleGuildChat','recordGuildChat','scrollGuildWindow','renderGuild'])assert.ok(declaration(name),`production ${name} helper missing`);
 class Node{constructor(){this.hidden=false;this.disabled=false;this.dataset={};this.children=[];this.value='';this.textContent='';this.id='';this.attributes={};this.scrollTop=0;this.scrollHeight=0;this.clientHeight=0;}replaceChildren(...children){this.children=[...children];}append(...children){this.children.push(...children);}setAttribute(name,value){this.attributes[name]=value;}}
 const nodes=Object.fromEntries(['guildStatus','guildCreateRow','guildMemberControls','guildManagement','guildCreate','guildWarRequest','guildCastleDialogue','guildAdd','guildRemove','guildNoticeSave','guildRanksSave','guildAlly','guildBreakAlly','guildOpen','guildMembersRequest','guildChatToggle','guildChatLog','guildScrollUp','guildScrollDown','guildNoticeInput','guildMembers','guildRelations','guildRanksElement','guildRanksInput'].map(name=>[name,new Node()]));nodes.guildMembers.id='guild-members';nodes.guildChatLog.id='guild-chat-log';
 const promptRequests=[],resolvePrompts=[],confirmationRequests=[],resolveConfirmations=[];let modalOpen=false;
 const context={...nodes,guildName:'赤月行会',guildRankName:'成员',guildNotice:'当前公告',guildCanManage:false,guildMemberPromptPending:undefined,guildMemberPromptSerial:0,guildActionPromptPending:undefined,guildActionPromptSerial:0,guildChatMode:false,guildChatEntries:[],guildNoticeDraft:'尚未保存的公告',guildRanksDraft:'#4 <堂主>\n小明',guildWarGuildNames:[],guildWarTimers:[],guildWarReceivedAt:0,guildAllyGuildNames:[],guildMemberNames:['小明'],guildRanks:[{rankNo:1,rankName:'会长',members:['会长']}],castleWarStatus:undefined,dialogueNpcId:7,guildPendingAction:undefined,guildScrollSpec:{stepRows:3,lineHeight:14},connection:{textContent:''},chat:[],sent:[],scrollCalls:[],scrollGuildMemberList:(list,direction,rows,lineHeight)=>{context.scrollCalls.push({list,direction,rows,lineHeight});return 0;},applyClassicChatColors:(node,foreground,background)=>{node.foreground=foreground;node.background=background;},appendChat:(channel,text)=>context.chat.push({channel,text}),worldCommandsAvailable:()=>true,systemDialog:{isOpen:()=>modalOpen,show:request=>{confirmationRequests.push(request);modalOpen=true;return new Promise(resolve=>resolveConfirmations.push(answer=>{modalOpen=false;resolve(answer);}));},showInput:request=>{promptRequests.push(request);modalOpen=true;return new Promise(resolve=>resolvePrompts.push(answer=>{modalOpen=false;resolve(answer);}));}},socket:{send:raw=>context.sent.push(JSON.parse(raw))},renderGuildRelations:()=>{},document:{body:{classList:{contains:value=>value==='in-world'}},createElement:()=>new Node()}};
 vm.createContext(context);vm.runInContext(compile(`${functions}\nrenderGuild()`),context);
 assert.equal(context.guildNoticeDraft,'尚未保存的公告');assert.equal(context.guildRanksDraft,'#4 <堂主>\n小明');assert.equal(context.guildAdd.disabled,true);assert.equal(context.guildNoticeSave.disabled,true);assert.equal(context.guildOpen.disabled,false);
 context.guildCanManage=true;vm.runInContext('renderGuild()',context);assert.equal(context.guildAdd.disabled,false);assert.equal(context.guildRanksSave.disabled,false);assert.equal(context.guildMemberControls.hidden,false);assert.equal(context.guildManagement.hidden,false);assert.equal(context.guildCreateRow.hidden,true,'guild creation is shown only without a guild at its NPC');
 context.guildCanManage=false;vm.runInContext('renderGuild()',context);assert.equal(context.guildMemberControls.hidden,true,'member-only guild roles must not see invite/remove controls');assert.equal(context.guildManagement.hidden,true,'member-only guild roles must not see manager controls');context.guildCanManage=true;
 vm.runInContext('toggleGuildChat()',context);assert.equal(context.guildChatMode,true);assert.equal(context.guildChatLog.hidden,false);assert.equal(context.guildMembers.hidden,true);assert.equal(context.guildRelations.hidden,true);assert.equal(context.guildRanksElement.hidden,true);assert.equal(context.guildChatToggle.attributes['aria-pressed'],'true');assert.equal(context.guildScrollUp.attributes['aria-controls'],'guild-chat-log');
 assert.equal(vm.runInContext("recordGuildChat('local','普通频道消息')",context),false);assert.equal(context.guildChatEntries.length,0);assert.equal(vm.runInContext("recordGuildChat('guild','行会频道消息',2,7)",context),true);assert.equal(context.guildChatEntries.length,1);assert.equal(context.guildChatLog.children[0].children[0].textContent,'行会频道消息');assert.equal(context.guildChatLog.children[0].children[0].foreground,2);assert.equal(context.guildChatLog.children[0].children[0].background,7);
 vm.runInContext('scrollGuildWindow(1)',context);assert.equal(context.scrollCalls.at(-1).list,context.guildChatLog);assert.deepEqual(context.scrollCalls.at(-1),{list:context.guildChatLog,direction:1,rows:3,lineHeight:14});
 vm.runInContext("guildChatEntries=[];guildChatLog.replaceChildren();for(let i=0;i<501;i++)recordGuildChat('guild',`消息${i}`)",context);assert.equal(context.guildChatEntries.length,400,'native 500-line chat history discards the oldest 101 together');assert.equal(context.guildChatEntries[0].text,'消息101');assert.equal(context.guildChatLog.children.length,400);
 vm.runInContext('toggleGuildChat()',context);assert.equal(context.guildChatMode,false);assert.equal(context.guildChatLog.hidden,true);assert.equal(context.guildMembers.hidden,false);assert.equal(context.guildRelations.hidden,false);assert.equal(context.guildScrollDown.attributes['aria-controls'],'guild-members');
 vm.runInContext('setGuildChatMode(true);guildName="";renderGuild()',context);assert.equal(context.guildChatMode,false,'leaving the guild resets the guild-chat view');context.guildName='赤月行会';
 vm.runInContext("syncGuildNotice('另一条服务器公告');renderGuild()",context);assert.equal(context.guildNoticeDraft,'尚未保存的公告','server refresh must preserve an unsaved notice draft');
 vm.runInContext("syncGuildNotice('尚未保存的公告');renderGuild()",context);assert.equal(context.guildNoticeDraft,undefined,'matching authoritative notice should clear the draft');
 vm.runInContext("syncGuildRanks([{rankNo:2,rankName:'副会长',members:['小明']}]);renderGuild()",context);assert.equal(context.guildRanksDraft,'#4 <堂主>\n小明','member refresh must preserve unsaved rank edits');
 vm.runInContext("syncGuildRanks([{rankNo:4,rankName:'堂主',members:['小明']}]);renderGuild()",context);assert.equal(context.guildRanksDraft,undefined,'matching authoritative ranks should clear the draft');
 assert.equal(vm.runInContext("guildActionForCommand('guildAdd')",context),'add');assert.equal(vm.runInContext("guildActionForResult('breakAlly')",context),'breakAlly');assert.equal(vm.runInContext("guildActionForCommand('guildNotice')",context),undefined);
 assert.equal(vm.runInContext("beginGuildAction('open','打开行会',()=>{sent.push('open')})",context),true);assert.deepEqual(context.sent,['open']);assert.equal(context.guildPendingAction.action,'open');assert.equal(context.guildStatus.dataset.pending,'true');assert.match(context.guildStatus.textContent,/正在打开行会/);for(const name of ['guildOpen','guildMembersRequest','guildAdd','guildRemove','guildNoticeSave','guildRanksSave','guildAlly','guildBreakAlly'])assert.equal(context[name].disabled,true,`${name} must lock during a guild request`);
 assert.equal(vm.runInContext("beginGuildAction('members','读取成员列表',()=>{sent.push('members')})",context),false);assert.deepEqual(context.sent,['open']);assert.equal(vm.runInContext("resolveGuildAction('members')",context),false);assert.equal(context.guildPendingAction.action,'open');
 assert.equal(vm.runInContext("handleGuildCommandError('guildMembers','成员读取失败')",context),true);assert.equal(context.guildPendingAction.action,'open','a different request error must not release the current wait');assert.equal(context.chat.at(-1).text,'行会操作失败：成员读取失败');
 assert.equal(vm.runInContext("handleGuildCommandError('guildOpen','当前没有行会')",context),true);assert.equal(context.guildPendingAction,undefined);assert.equal(context.guildStatus.dataset.pending,'false');assert.equal(context.guildOpen.disabled,false);assert.equal(context.connection.textContent,'当前没有行会');
 assert.equal(vm.runInContext("beginGuildAction('add','邀请成员',()=>true)",context),true);assert.equal(vm.runInContext("handleGuildCommandError('guildAdd','对方拒绝')",context),true);assert.equal(context.guildPendingAction,undefined);
 assert.equal(vm.runInContext("beginGuildAction('breakAlly','解除联盟',()=>false)",context),false);assert.equal(context.guildPendingAction,undefined);assert.match(context.connection.textContent,/发送失败/);
 assert.equal(vm.runInContext("beginGuildAction('remove','移除成员',()=>{throw new Error('offline')})",context),false);assert.equal(context.guildPendingAction,undefined);assert.match(context.connection.textContent,/发送失败/);
 await (async()=>{
  vm.runInContext("confirmGuildMemberAction('guildAdd')",context);assert.equal(promptRequests.at(-1).text,'请输入您想要让加入行会的玩家姓名： 赤月行会.');assert.equal(context.guildMemberPromptPending.action,'guildAdd');assert.equal(context.guildAdd.disabled,true);
  resolvePrompts.shift()({result:'cancel',value:''});await new Promise(resolve=>setImmediate(resolve));assert.equal(context.guildMemberPromptPending,undefined);assert.equal(context.sent.filter(value=>typeof value==='object').length,0,'cancelled invite must not send a guild command');
  vm.runInContext("confirmGuildMemberAction('guildAdd')",context);resolvePrompts.shift()({result:'ok',value:' 小明 '});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(context.sent.filter(value=>typeof value==='object').at(-1),{type:'guildAdd',target:'小明'});assert.equal(context.guildPendingAction.action,'add');vm.runInContext("resolveGuildAction('add')",context);
  vm.runInContext("confirmGuildMemberAction('guildRemove')",context);assert.equal(promptRequests.at(-1).text,'请输入您想从行会删除的玩家姓名：');resolvePrompts.shift()({result:'ok',value:'  '});await new Promise(resolve=>setImmediate(resolve));assert.equal(context.sent.filter(value=>typeof value==='object').length,1,'empty member name must not send a guild command');assert.equal(context.connection.textContent,'请填写角色名');
  vm.runInContext("confirmGuildMemberAction('guildRemove')",context);resolvePrompts.shift()({result:'ok',value:'小明'});await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(context.sent.filter(value=>typeof value==='object').at(-1),{type:'guildRemove',target:'小明'});assert.equal(context.guildPendingAction.action,'remove');vm.runInContext("resolveGuildAction('remove')",context);
  vm.runInContext("confirmGuildMemberAction('guildAdd')",context);context.guildCanManage=false;resolvePrompts.shift()({result:'ok',value:'小明'});await new Promise(resolve=>setImmediate(resolve));assert.equal(context.sent.filter(value=>typeof value==='object').length,2,'a role change while the prompt is open must invalidate submission');assert.match(context.connection.textContent,/行会状态已变化/);context.guildCanManage=true;
 })();
 await (async()=>{
  const sentBefore=context.sent.filter(value=>typeof value==='object').length;
  vm.runInContext("confirmGuildAction('ally')",context);assert.deepEqual(Array.from(confirmationRequests.at(-1).buttons),['ok','cancel']);assert.equal(context.guildActionPromptPending.action,'ally');assert.equal(context.guildAlly.disabled,true,'a pending modal decision locks the underlying guild controls');
  resolveConfirmations.shift()('cancel');await new Promise(resolve=>setImmediate(resolve));assert.equal(context.sent.filter(value=>typeof value==='object').length,sentBefore,'cancelled alliance confirmation must not send');
  vm.runInContext("confirmGuildAction('ally')",context);resolveConfirmations.shift()('ok');await new Promise(resolve=>setImmediate(resolve));assert.deepEqual(context.sent.filter(value=>typeof value==='object').at(-1),{type:'guildAlly'},'native alliance request identifies the adjacent leader, not a typed target');assert.equal(context.guildPendingAction.action,'ally');vm.runInContext("resolveGuildAction('ally')",context);
  vm.runInContext("confirmGuildAction('breakAlly')",context);assert.equal(promptRequests.at(-1).text,'请输入需要解除联盟的行会名：');assert.equal(promptRequests.at(-1).input.label,'行会名');resolvePrompts.shift()({result:'cancel',value:''});await new Promise(resolve=>setImmediate(resolve));assert.equal(context.sent.filter(value=>typeof value==='object').length,sentBefore+1,'cancelled break-alliance input must not send');
  vm.runInContext("confirmGuildAction('breakAlly')",context);resolvePrompts.shift()({result:'ok',value:'  '});await new Promise(resolve=>setImmediate(resolve));assert.equal(context.sent.filter(value=>typeof value==='object').length,sentBefore+1,'empty target must not send');
  vm.runInContext("confirmGuildAction('breakAlly')",context);context.guildCanManage=false;resolvePrompts.shift()({result:'ok',value:'友好行会'});await new Promise(resolve=>setImmediate(resolve));assert.equal(context.sent.filter(value=>typeof value==='object').length,sentBefore+1,'permission changes while the prompt is open must invalidate the request');assert.match(context.connection.textContent,/行会状态已变化/);context.guildCanManage=true;
  vm.runInContext("confirmGuildAction('ally')",context);vm.runInContext('cancelGuildActionPrompt()',context);resolveConfirmations.shift()('ok');await new Promise(resolve=>setImmediate(resolve));assert.equal(context.sent.filter(value=>typeof value==='object').length,sentBefore+1,'disconnect/reset invalidation must discard a stale confirmation');
 })();
 assert.match(play,/resolveGuildAction\('open'\);setGuildChatMode\(false\);if\(guildEditor\.isOpen\(\)&&\(guildName!==message\.guildName\|\|message\.canManage!==true\)\)guildEditor\.cancel\(\);if\(guildName&&guildName!==message\.guildName\)\{guildNoticeDraft=undefined;guildRanksDraft=undefined;\}guildName=message\.guildName/);assert.match(play,/resolveGuildAction\('members'\);setGuildChatMode\(false\);guildMemberNames=/);assert.match(play,/guildActionForResult\(message\.action\);if\(action\)resolveGuildAction\(action\)/);assert.match(play,/\['guildOpen','guildMembers','guildAdd','guildRemove','guildNotice','guildRanks','guildAlly','guildBreakAlly'\]\.includes\(message\.commandType\)&&handleGuildCommandError\(message\.commandType,message\.message\)\)return;/);assert.match(play,/groupPending=undefined;groupFeedbackText='';attackMode=0;attackModePending=undefined;attackModeCommandChatId=undefined;attackModeNotice='';guildPendingAction=undefined/,'disconnect/world clear must release pending social and attack-mode requests');
 assert.match(play,/guildCanManage=message\.canManage===true/);
 console.log('PASS: guild retains native action frames and drafts, serializes ACK-backed actions, and isolates guild errors from unrelated pending state');
}

{
 const sourceFile=ts.createSourceFile('play.ts',play,ts.ScriptTarget.Latest,true),declaration=name=>sourceFile.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text===name)?.getText(sourceFile);
 const request=declaration('requestTradeWithPlayer'),render=declaration('renderTargets');assert.ok(request&&render,'production nearby-player trade action missing');
 class Element{constructor(){this.children=[];this.dataset={};this.disabled=false;this.hidden=false;this.textContent='';this.className='';this.title='';}replaceChildren(...children){this.children=[...children];this.textContent='';}append(...children){this.children.push(...children);}}
 const actor={id:1,self:true,x:10,y:10,feature:0,name:'Me'},near={id:2,self:false,x:11,y:10,feature:0,name:'Alice'},far={id:3,self:false,x:12,y:10,feature:0,name:'Bob'},slave={id:4,self:false,x:10,y:11,feature:0,name:'召唤物',kind:'slave',nameColor:254},monster={id:5,self:false,x:10,y:11,feature:1,name:'骷髅'};
 const nodes=[],context={targetsElement:new Element(),nearbyTradeButtons:[],entities:new Map([[1,actor],[2,near],[3,far],[4,slave],[5,monster]]),self:1,tradeRequestPending:false,tradeTarget:{value:'伪造名字'},tradeRequestButton:{id:'submit'},tradeRequestForm:{submitted:[],requestSubmit(button){this.submitted.push(button);}},worldCommandsAvailable:()=>true,showClassicWindow:id=>nodes.push(id),interact(){},requestsHarvest:()=>false,document:{createElement:()=>new Element()}};
 vm.createContext(context);vm.runInContext(ts.transpileModule(`${request}\n${render}`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);context.renderTargets();
 const rows=context.targetsElement.children,alice=rows.find(row=>row.children[0].dataset.entityId==='2'),bob=rows.find(row=>row.children[0].dataset.entityId==='3'),summon=rows.find(row=>row.children[0].dataset.entityId==='4');
 assert.ok(alice&&bob&&summon);assert.equal(alice.children.length,2);assert.equal(alice.children[1].textContent,'邀请交易');assert.equal(alice.children[1].disabled,false);assert.equal(bob.children[1].textContent,'需相邻交易');assert.equal(bob.children[1].disabled,true);assert.equal(summon.children.length,1,'summons are not offered as trade recipients');
 let prevented=false,stopped=false;alice.children[1].onclick({preventDefault(){prevented=true;},stopPropagation(){stopped=true;}});assert.equal(prevented,true);assert.equal(stopped,true);assert.equal(context.tradeTarget.value,'Alice','request uses the current server-projected actor name, replacing typed text');assert.deepEqual(nodes,['trade']);assert.deepEqual(context.tradeRequestForm.submitted,[context.tradeRequestButton]);
 context.tradeRequestPending=true;assert.equal(context.requestTradeWithPlayer(2),false,'a second invitation is refused while the request is pending');assert.equal(context.tradeRequestForm.submitted.length,1);
 context.tradeRequestPending=false;context.entities.set(2,{...near,x:12});assert.equal(context.requestTradeWithPlayer(2),false,'a player that is no longer adjacent cannot be invited from a stale target control');assert.equal(context.tradeRequestForm.submitted.length,1);
 assert.equal(context.requestTradeWithPlayer(5),false,'a monster cannot be sent as a player trade recipient');assert.equal(context.requestTradeWithPlayer(99),false,'a removed entity cannot be sent as a trade recipient');
 console.log('PASS: nearby player trade action uses current server identity, requires adjacency, excludes summons/monsters and respects the pending lock');
}


{
 const editorSource=fs.readFileSync(path.join(root,'apps/web/src/guild-editor.ts'),'utf8');
 const editorCss=fs.readFileSync(path.join(root,'apps/web/src/guild-editor.css'),'utf8');
 const source=ts.createSourceFile('guild-editor.ts',editorSource,ts.ScriptTarget.Latest,true);
 const parse=source.statements.find(node=>ts.isFunctionDeclaration(node)&&node.name?.text==='parseGuildRankDraft');assert.ok(parse,'guild rank parser missing');
 const context={exports:{}};vm.createContext(context);vm.runInContext(ts.transpileModule(parse.getText(source),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,context);const parseGuildRankDraft=context.exports.parseGuildRankDraft;
 const parsed=parseGuildRankDraft('#1 <會長>\n小明\n#4 <堂主>\nAlice\n小王');assert.equal(parsed.error,undefined);assert.deepEqual(JSON.parse(JSON.stringify(parsed.ranks)),[{no:1,name:'會長',members:['小明']},{no:4,name:'堂主',members:['Alice','小王']}]);
 assert.match(parseGuildRankDraft('').error,/至少填写一个/);assert.match(parseGuildRankDraft('#1 <会长>\n小明\n#2 <副会长>\nAlice|other').error,/成员名/);const tooMany=Array.from({length:21},(_,index)=>`#${index+1} <职位>`).join('\n');assert.match(parseGuildRankDraft(tooMany).error,/20/);
 assert.match(markup,/id="guild-notice-save"[^>]*aria-label="编辑行会公告"/);assert.match(markup,/id="guild-ranks-save"[^>]*aria-label="编辑行会封号"/);assert.doesNotMatch(markup,/id="guild-notice"|id="guild-ranks-input"/,'guild editors should not remain permanently visible on the guild window');
 assert.match(play,/guildEditor\.open\(\{kind:'notice'/);assert.match(play,/guildEditor\.open\(\{kind:'ranks'/);assert.match(play,/guildEditor\.cancel\(\);systemDialog\.interrupt\(\)/);
 for(const [pattern,label] of [[/left:96px;top:136px;box-sizing:border-box;width:608px;height:327px/,'Prguse#204 geometry'],[/left:16px;top:36px;box-sizing:border-box;width:571px;height:246px/,'native memo placement'],[/left:514px;top:287px;width:80px;height:34px/,'native OK button'],[/left:584px;top:6px;width:16px;height:23px/,'native close button']])assert.match(editorCss,pattern,label+' missing');
 for(const [index,size] of [[204,[608,327]],[361,[80,34]],[64,[16,23]]])assert.deepEqual([library.frames[String(index)].width,library.frames[String(index)].height],size,'Prguse#'+index+' dimensions changed');
 assert.match(gateway,/GetArrayLength\(\) is < 1 or > 20/);assert.match(gateway,/Guild ranks are too large/);
 console.log('PASS: guild notice and rank editing use the native memo dialog, cancel safely, and validate gateway rank limits');
}
