import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';

const source=fs.readFileSync('apps/web/src/resource-diagnostics.ts','utf8');
const context={exports:{}};vm.createContext(context);
vm.runInContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);
const {iconDiagnostics,resourceHasIdentityConflict,mapBindingStatus,mapBindingDiagnostics,mapBindingNeedsReview}=context.exports;
const catalog=JSON.parse(fs.readFileSync('content/classic-176/resource-catalog.json','utf8'));
const armour=catalog.items.find(item=>item.name==='雷霆战甲(男)');
const poison=catalog.skills.find(skill=>skill.name==='群体施毒术');
assert.match(iconDiagnostics(armour),/索引超出当前源范围/);assert.match(iconDiagnostics(armour),/869/);assert.match(iconDiagnostics(armour),/570/);
assert.match(iconDiagnostics(armour),/未选作生效素材/);assert.doesNotMatch(iconDiagnostics(armour),/<img|<a /);
console.log('PASS actual missing extension item identifies exact range and never previews an unselected candidate');
assert.equal(resourceHasIdentityConflict(poison),true);assert.match(iconDiagnostics(poison),/编号与其他效果冲突/);
assert.equal(resourceHasIdentityConflict(catalog.skills.find(skill=>skill.name==='火球术')),false);
console.log('PASS SQL skill identity conflict is visible independently of icon availability');
assert.equal(iconDiagnostics({}), '');
assert.match(iconDiagnostics({iconResolution:{index:0,sourceFrameCount:0,sourceVerified:false}}),/精确索引<\/span><strong>0/);
assert.match(iconDiagnostics({iconResolution:{sourceVerified:false}}),/未通过/);
console.log('PASS absent diagnostics do not invent provenance and zero indexes remain distinct from missing fields');
const escaped=iconDiagnostics({missingReason:'<script>x</script>',iconResolution:{sourceId:'<img src=x>',namespace:'" onclick="x',candidates:[{sourceId:'<svg onload=x>',namespace:'javascript:x',selected:false}]}});
assert.doesNotMatch(escaped,/<script|<img|<svg|onclick="/);assert.match(escaped,/&lt;script&gt;/);
console.log('PASS diagnostic source strings stay escaped as text');

// Execute actual page branches using production diagnostics, with only layout
// helpers stubbed. This is Node/VM evidence, not a browser rendering assertion.
const page=fs.readFileSync('apps/web/src/resource-manager.ts','utf8');
const ast=ts.createSourceFile('resource-manager.ts',page,ts.ScriptTarget.Latest,true);
const functions=ast.statements.filter(node=>ts.isFunctionDeclaration(node)&&['lacks','tags','renderDetail'].includes(node.name?.text)).map(node=>node.getText(ast)).join('\n');
assert.equal(functions.split('function ').length-1,3);
const pageContext={catalog,section:'items',detail:{innerHTML:''},iconDiagnostics,resourceHasIdentityConflict,mapBindingStatus,mapBindingDiagnostics,mapBindingNeedsReview,
 heading:()=>'<header/>',properties:()=>'',relation:()=>'',escape:value=>String(value)};
vm.createContext(pageContext);vm.runInContext(ts.transpileModule(functions,{compilerOptions:{module:ts.ModuleKind.None,target:ts.ScriptTarget.ES2022}}).outputText,pageContext);
pageContext.renderDetail(armour);assert.match(pageContext.detail.innerHTML,/resource-icon-diagnostics/);assert.match(pageContext.detail.innerHTML,/索引超出/);
console.log('PASS actual item detail branch attaches current source diagnostics');
pageContext.section='skills';pageContext.renderDetail(poison);assert.match(pageContext.detail.innerHTML,/编号与其他效果冲突/);
assert.equal(pageContext.lacks({...poison,rulePinned:true,iconUrl:'/valid.png'}),true);
assert.equal(pageContext.lacks({rulePinned:true,iconUrl:'/valid.png',pressedIconUrl:'/pressed.png',identityStatus:'ok'}),false);
assert.equal(pageContext.lacks({rulePinned:true,iconUrl:'/valid.png',pressedIconUrl:null,identityStatus:'ok'}),true);
console.log('PASS actual skill detail and missing filter retain identity conflicts even with a drawable icon');
const potion=catalog.items.find(item=>item.name==='金创药(特量)');
assert.match(iconDiagnostics(potion),/旧拟议索引<\/span><strong>813/);
assert.match(iconDiagnostics(potion),/精确索引<\/span><strong>5022/);
assert.match(iconDiagnostics(poison),/按下帧索引<\/span><strong>55/);
console.log('PASS proposed legacy mappings and pressed frames are distinct from selected raw source indexes');
pageContext.section='assets';
const candidate=catalog.assets.find(asset=>asset.id==='libraries/reference-ga0/Tiles');
assert.equal(candidate.sourceRole,'reference_candidate');assert.equal(candidate.mapBindingActive,true);
assert.equal(candidate.exportSnapshotMapBindingActive,false);
assert.equal(pageContext.lacks(candidate),true);
assert.equal(pageContext.lacks({missing:0,sourceRole:'unknown'}),true);
assert.equal(pageContext.lacks({missing:0,sourceRole:'active_required'}),false);
console.log('PASS actual asset filter keeps selected reference pairing and unknown identities open even with all requested PNGs');
assert.match(mapBindingStatus(candidate),/GA0参考源已选择，原版配对待核/);
pageContext.renderDetail(candidate);
assert.match(pageContext.detail.innerHTML,/408 个原索引/);assert.match(pageContext.detail.innerHTML,/当前渲染已选择/);
assert.match(pageContext.detail.innerHTML,/原版配对待核/);assert.doesNotMatch(pageContext.detail.innerHTML,/<img/);
pageContext.section='maps';pageContext.renderDetail(catalog.maps.find(map=>map.id==='GA0'));
assert.match(pageContext.detail.innerHTML,/resource-map-bindings/);
console.log('PASS actual map and library detail distinguish current reference selection from historical pairing');
const pending={sourceRole:'reference_candidate',mapBindingActive:true,mapSourceSelections:[{mapId:'GA0',selected:false,manifestLocksMatch:true,indexCount:408}]};
assert.equal(mapBindingStatus(pending),'参考候选，未绑定');
assert.match(mapBindingDiagnostics(pending),/未选择/);
assert.equal(mapBindingStatus({...pending,mapSourceSelections:[{selected:true,manifestLocksMatch:false}]}),'参考候选，未绑定');
assert.equal(mapBindingDiagnostics({}), '');
assert.doesNotMatch(mapBindingDiagnostics({mapSourceSelections:[{mapId:'<img src=x>',layer:'<svg onload=x>',indexCount:0,selectionEvidence:'<script>x</script>'}]}),/<img|<svg|<script/);
console.log('PASS stale export booleans, pending selections and mismatched locks cannot impersonate current source use');
pageContext.section='maps';
const withMinimap={...catalog.maps.find(map=>map.id==='GA0'),minimapUrl:'/valid.png'};
assert.equal(pageContext.lacks(withMinimap),true);assert.match(pageContext.tags(withMinimap),/存在缺失项/);assert.doesNotMatch(pageContext.tags(withMinimap),/关联完整/);
assert.equal(pageContext.lacks({...withMinimap,mapSourceSelections:[]}),false);
const failed={...withMinimap,mapSourceSelections:[{status:'enabled',selected:false,manifestLocksMatch:false,historicalPairingVerified:true}]};
assert.equal(pageContext.lacks(failed),true);assert.match(pageContext.tags(failed),/存在缺失项/);
console.log('PASS actual map filtering and tags retain pairing or enabled-lock failures even when geometry and minimap are complete');
