from pathlib import Path
import sys
import unittest
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'tools'))
from item_codec import parse_client_item


class ItemCodecTests(unittest.TestCase):
    def test_native_server_generated_fixture(self):
        # Generated by the actual ClientItem.GetBuffer in CoreRegression.
        raw = bytes.fromhex((Path(__file__).parent / 'fixtures/native-client-item.hex').read_text())
        item = parse_client_item(raw)
        self.assertEqual(item['name'], '鸡肉')
        self.assertEqual(item['makeIndex'], 0x12345678)
        self.assertEqual(item['durability'], 1234)
        self.assertEqual(item['maxDurability'], 4000)
        self.assertEqual(item['stdMode'], 40)
        self.assertEqual(item['weight'], 1)
        for bad in (raw[:-1], raw+b'\x00'):
            with self.assertRaises(ValueError):
                parse_client_item(bad)
